# Embeds shader files verbatim into a C++ header, as a map from base filename to contents.
#
# Used for shader sources that Aurora does not own, and therefore cannot minify or edit, but must
# still hand to the Slang transpiler at runtime -- notably the NRD SDK's NRD.hlsli. Embedding them
# means a build of Aurora carries every shader source it needs, so nothing has to be deployed
# alongside the binaries and an integrator needs no extra files.

import os
import sys

# Dump usage and exit if we have too few args.
if len(sys.argv) < 4:
    print("Usage: python embedShaderFiles.py outputFile namespace inputFile [inputFile ...]")
    print("  outputFile - Output C++ header file")
    print("  namespace  - Namespace to wrap the embedded contents in")
    print("  inputFile  - Shader file to embed; accessible by its base name")
    sys.exit(-1)

outputFile = sys.argv[1]
nameSpaceName = sys.argv[2]
inputFiles = sys.argv[3:]

# MSVC rejects any single string literal longer than 16380 bytes (C2026), and caps a run of
# *concatenated* literals at 65535 bytes. So each file is emitted as an array of independent
# literals joined at runtime, which is subject to neither limit. The chunk size stays well under
# the per-literal cap because one source byte can expand to a four character escape.
kMaxChunkLength = 2000

# Characters that need an escape, mapped to it. Everything else printable is passed through, and
# everything else is emitted as a three digit octal escape -- which, unlike \x, cannot swallow a
# following character that happens to be a hex digit.
kEscapes = {
    ord("\\"): "\\\\",
    ord('"'): '\\"',
    ord("\n"): "\\n",
    ord("\r"): "\\r",
    ord("\t"): "\\t",
    # "??" begins a trigraph in C++14 and earlier; escaping the second one is always safe.
    ord("?"): "\\?",
}


# The C++ escaped form of a single source byte.
def escapeByte(byte):
    if byte in kEscapes:
        return kEscapes[byte]
    if 0x20 <= byte <= 0x7E:
        return chr(byte)
    return "\\%03o" % byte


# Splits the escaped form of data into chunks, never cutting an escape sequence in half.
def toChunks(data):
    chunks = []
    current = ""
    for byte in data:
        escaped = escapeByte(byte)
        if len(current) + len(escaped) > kMaxChunkLength:
            chunks.append(current)
            current = ""
        current += escaped
    chunks.append(current)
    return chunks


# A C++ identifier fragment for a filename, e.g. "NRD.hlsli" -> "NRD_hlsli".
def toIdentifier(name):
    return "".join(c if c.isalnum() else "_" for c in name)


try:
    headerOutput = open(outputFile, "w")
except:
    print("Failed to open output header: " + outputFile)
    sys.exit(-1)

headerOutput.write("// Shader files embedded verbatim as C++ strings.\n")
headerOutput.write(
    "// Automatically generated by " + os.path.basename(sys.argv[0]) + "; do not edit.\n"
)
headerOutput.write("\n#include <map>\n#include <string>\n\n")
headerOutput.write("namespace " + nameSpaceName + " {\nnamespace detail {\n")

entries = []
for inputFile in inputFiles:
    baseFilename = os.path.basename(inputFile)
    print("\t Embedding %s" % inputFile)
    try:
        with open(inputFile, "rb") as inputStream:
            data = inputStream.read()
    except:
        print("Failed to open: " + inputFile)
        sys.exit(-1)

    symbolName = "kChunks_" + toIdentifier(baseFilename)
    entries.append((baseFilename, symbolName))

    headerOutput.write(
        "\n// Verbatim copy of " + baseFilename + " (" + str(len(data)) + " bytes).\n"
    )
    headerOutput.write("static const char* const " + symbolName + "[] = {\n")
    for chunk in toChunks(data):
        headerOutput.write('    "' + chunk + '",\n')
    headerOutput.write("    nullptr,\n};\n")

headerOutput.write(
    """
// Concatenates a null terminated array of literals into one string.
inline std::string join(const char* const* pChunks)
{
    std::string result;
    for (; *pChunks; pChunks++)
    {
        result += *pChunks;
    }
    return result;
}

} // namespace detail

// The embedded files, keyed by base filename.
inline const std::map<std::string, std::string>& directory()
{
    static const std::map<std::string, std::string> sDirectory = {
"""
)
for baseFilename, symbolName in entries:
    headerOutput.write(
        '        { "%s", detail::join(detail::%s) },\n' % (baseFilename, symbolName)
    )
headerOutput.write(
    """    };
    return sDirectory;
}

} // namespace """
    + nameSpaceName
    + "\n"
)

headerOutput.close()
print("Embedded %d file(s) into %s" % (len(inputFiles), outputFile))
