// Copyright 2026 Autodesk, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#include "pch.h"

#include <fstream>
#include <iostream>

#include "BSDFCodeGenerator.h"

// MaterialX headers.
#include <MaterialXCore/Generated.h>
#if MATERIALX_MAJOR_VERSION < 1 || \
    (MATERIALX_MAJOR_VERSION == 1 && MATERIALX_MINOR_VERSION < 39) || \
    (MATERIALX_MAJOR_VERSION == 1 && MATERIALX_MINOR_VERSION == 39 && MATERIALX_BUILD_VERSION < 5)
#error "MaterialX 1.39.5 or later is required for slang shader generation support."
#endif
#include <MaterialXCore/Document.h>
#include <MaterialXFormat/Util.h>
#include <MaterialXFormat/XmlIo.h>
#include <MaterialXGenSlang/SlangShaderGenerator.h>
#include <MaterialXGenSlang/SlangSyntax.h>
#include <MaterialXGenShader/DefaultColorManagementSystem.h>
#include <MaterialXGenShader/HwShaderGenerator.h>
#include <MaterialXGenShader/Shader.h>
#include <MaterialXGenShader/ShaderStage.h>
#include <MaterialXGenShader/Util.h>
#include <MaterialXRender/LightHandler.h>

#include <iomanip>
#include <sstream>

namespace Aurora
{
namespace MaterialXCodeGen
{

shared_ptr<MaterialX::Document> BSDFCodeGenerator::s_pStdLib;

// The name given to the top-level ShaderGraph created from the surface shader element.
// This name appears on connections from interface inputs back to the top-level graph node.
static constexpr const char* kShaderGraphName = "BSDFCodeGeneratorShaderGraph";

// Custom shader class used by BSDFCodeGenerator.
class BSDFCodeGeneratorShader : public MaterialX::Shader
{
public:
    // Same ctor arguments as parent class.
    BSDFCodeGeneratorShader(const string& name, MaterialX::ShaderGraphPtr graph) :
        MaterialX::Shader(name, graph)
    {
        _pSyntax = make_shared<MaterialX::SlangSyntax>(MaterialX::TypeSystem::create());

        // A dummy "pixel" stage is used to generate the BSDF code.
        _pStage = make_shared<MaterialX::ShaderStage>(MaterialX::Stage::PIXEL, _pSyntax);
        _stagesMap[MaterialX::Stage::PIXEL] = _pStage;
        _stages.push_back(_pStage.get());

        // Create an input block for the vertex data (stored in global struct)
        auto vd = _pStage->createInputBlock(MaterialX::HW::VERTEX_DATA);
        vd->setInstance("vertexData");

        // Add the required vertex attributes.
        // TODO: These are just educated guesses. How do we work out which attributes are used?
        auto tc0 = vd->add(MaterialX::Type::VECTOR2, MaterialX::HW::T_TEXCOORD + "_0");
        tc0->setVariable("texCoord");
        auto no = vd->add(MaterialX::Type::VECTOR3, MaterialX::HW::T_NORMAL_OBJECT);
        no->setVariable("objectNormal");
        auto nw = vd->add(MaterialX::Type::VECTOR3, MaterialX::HW::T_NORMAL_WORLD);
        nw->setVariable("normal");
        auto tw = vd->add(MaterialX::Type::VECTOR3, MaterialX::HW::T_TANGENT_WORLD);
        tw->setVariable("tangent");
#if MATERIALX_MAJOR_VERSION >= 1 && MATERIALX_MINOR_VERSION >= 39
        auto bw = vd->add(MaterialX::Type::VECTOR3, MaterialX::HW::T_BITANGENT_WORLD);
        bw->setVariable("bitangentWorld");
#endif
        auto po = vd->add(MaterialX::Type::VECTOR3, MaterialX::HW::T_POSITION_OBJECT);
        po->setVariable("objectPosition");
        auto pw = vd->add(MaterialX::Type::VECTOR3, MaterialX::HW::T_POSITION_WORLD);
        pw->setVariable("position");
    }

    // Get the shader stage created by this shader class.
    shared_ptr<MaterialX::ShaderStage> stage() { return _pStage; }

    // Get the syntax object created by this shader class.
    shared_ptr<MaterialX::SlangSyntax> syntax() { return _pSyntax; }

    // Get the source that was generated by the last emit call.
    string getNewSource()
    {
        const string& allSource = _pStage->getSourceCode();
        size_t p                = _currSourcePosition;
        _currSourcePosition     = allSource.size();
        return allSource.substr(p);
    }

private:
    size_t _currSourcePosition = 0;
    shared_ptr<MaterialX::ShaderStage> _pStage;
    shared_ptr<MaterialX::SlangSyntax> _pSyntax;
};

// Custom shader generator class used by BSDFCodeGenerator.
class BSDFShaderGenerator : public MaterialX::SlangShaderGenerator
{
public:
    BSDFShaderGenerator(const string& mtlxLibPath) :
        MaterialX::SlangShaderGenerator(MaterialX::TypeSystem::create()),
        _mtlxLibPath(mtlxLibPath)
    {
        _pGeneratedIncludes    = make_unique<map<string, string>>();
        _pGeneratedDefinitions = make_unique<map<size_t, string>>();
    }

    virtual void emitFunctionDefinition(const MaterialX::ShaderNode& node,
        MaterialX::GenContext& context, MaterialX::ShaderStage& stage) const override
    {
        // Get implementation for node.
        const MaterialX::ShaderNodeImpl& impl = node.getImplementation();
        size_t implHash                       = impl.getHash();

        // Check if we've already generated this implementation.
        // There are lots of checks like this around, but the only way to reliably ensure we don't
        // have duplicated functions is to do it here in the code generator.
        // TODO: Work out a nicer way of doing this.
        if (_pGeneratedDefinitions->find(implHash) != _pGeneratedDefinitions->end())
        {
            return;
        }

        // Add to the map so not emitted next time.
        _pGeneratedDefinitions->insert({ implHash, node.getName() });

        // If not a duplicate just pass to the generator.
        MaterialX::SlangShaderGenerator::emitFunctionDefinition(node, context, stage);

        // Replace tokens in source code.
        auto code = stage.getSourceCode();
        MaterialX::tokenSubstitution(context.getShaderGenerator().getTokenSubstitutions(), code);
        stage.setSourceCode(code);
    }

    virtual void emitBlock(const string& str, const MaterialX::FilePath& sourceFilename,
        MaterialX::GenContext& context, MaterialX::ShaderStage& stage) const override
    {
        // Build processed block of source from original.
        string processedBlock = "";

        // Stream the source from original string.
        MaterialX::StringStream stream(str);
        for (string line; std::getline(stream, line);)
        {

            // Look for #include lines, so we can have a custom include functionality.
            size_t pos = line.find("#include");
            if (pos != string::npos)
            {
                // Decode the include line.
                size_t startQuote = line.find_first_of("\"");
                size_t endQuote   = line.find_last_of("\"");
                if (startQuote != string::npos && endQuote != string::npos && endQuote > startQuote)
                {
                    size_t length = (endQuote - startQuote) - 1;
                    if (length)
                    {
                        // Get filename from line.
                        const string filename = line.substr(startQuote + 1, length);

                        // Ensure this include has not been included before, if it has ignore this
                        // line. There are lots of checks like this around, but the only way to
                        // reliably ensure we don't have duplicated functions is to do it here in
                        // the code generator.
                        // TODO: Work out a nicer way of doing this.
                        if (_pGeneratedIncludes->find(filename) == _pGeneratedIncludes->end())
                        {
                            // Check if we have a custom path mapping for this include.
                            auto pathIter = _includeFilePaths.find(filename);
                            if (pathIter != _includeFilePaths.end())
                            {
                                // Empty value: already defined in MaterialXCommon.slang; skip.
                                if (pathIter->second.empty())
                                {
                                    _pGeneratedIncludes->insert({ filename, "" });
                                }
                                else
                                {
                                    const string resolvedPath =
                                        context.resolveSourceFile(pathIter->second, _mtlxLibPath);
                                    _pGeneratedIncludes->insert({ filename, resolvedPath });
                                    string source = MaterialX::readFile(resolvedPath);
                                    if (source.empty())
                                    {
                                        AU_ERROR("Failed to load MaterialX include file:%s",
                                            resolvedPath.c_str());
                                    }
                                    processedBlock +=
                                        "// Included from " + filename + "\n" + source + "\n";
                                }
                            }
                            else
                            {
                                // No custom mapping — attempt direct resolution via the MaterialX
                                // library search path and inline the file if found.
                                const string resolvedPath =
                                    context.resolveSourceFile(filename, _mtlxLibPath);
                                _pGeneratedIncludes->insert({ filename, resolvedPath });
                                string source = MaterialX::readFile(resolvedPath);
                                if (!source.empty())
                                {
                                    processedBlock +=
                                        "// Included from " + filename + "\n" + source + "\n";
                                }
                                else
                                {
                                    // If not found, emit the #include as-is and let the Slang
                                    // compiler resolve it.
                                    processedBlock += line + "\n";
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                // All other lines are added with
                processedBlock += line + "\n";
            }
        }

        // Pass the processed block (without include lines) to the parent class emitBlock function.
        MaterialX::SlangShaderGenerator::emitBlock(processedBlock, sourceFilename, context, stage);
    }

    // Replace the upstream result with a temp variable if node+input name match.
    string getUpstreamResult(
        const MaterialX::ShaderInput* input, MaterialX::GenContext& context) const override
    {
        // Use temp variable if full name matches.
        string fullName = input->getNode()->getName() + "_" + input->getName();
        if (_tempVariables.find(fullName) != _tempVariables.end())
        {
            return _tempVariables.at(fullName);
        }

        // Otherwise call parent class method.
        string result = MaterialX::SlangShaderGenerator::getUpstreamResult(input, context);
        return result;
    }

    // Add a temp variable for given input.
    void addTempInputVariable(const MaterialX::ShaderInput* input, string tempName)
    {
        string fullName = input->getNode()->getName() + "_" + input->getName();

        _tempVariables[fullName] = tempName;
    }

    // Clear all the temp variables.
    void clearTempVariables() { _tempVariables.clear(); }

    // Clear the generated definitions and includes.
    void clearGeneratedDefinitions()
    {
        _pGeneratedDefinitions->clear();
        _pGeneratedIncludes->clear();
    }

protected:
    map<string, string> _tempVariables;
    unique_ptr<map<size_t, string>> _pGeneratedDefinitions;
    unique_ptr<map<string, string>> _pGeneratedIncludes;
    string _mtlxLibPath;

    // Remap GLSL stdlib includes to Slang-native equivalents.
    // An empty value means the function is already defined in MaterialXCommon.slang;
    // the include line is silently skipped.
    map<string, string> _includeFilePaths = { { "lib/$fileTransformUv", "" } };
};

void BSDFCodeGenerator::createStdLib()
{
    // Setup search path.
    MaterialX::FilePathVec libraryFolders;
    libraryFolders.push_back(_mtlxLibPath);
    MaterialX::FileSearchPath searchPath;
    searchPath.append(_mtlxLibPath.c_str());

    // Create a document to store standard library.
    s_pStdLib = MaterialX::createDocument();

    // Load the standard library.
    auto res = MaterialX::loadLibraries(libraryFolders, searchPath, s_pStdLib);
    AU_ASSERT(
        res.size(), "Failed to load MaterialX standard libraries from %s\n", _mtlxLibPath.c_str());
}

BSDFCodeGenerator::BSDFCodeGenerator(
    const string& mtlxPath, const string& surfaceShaderNodeCategory) :
    _surfaceShaderNodeCategory(surfaceShaderNodeCategory)
{
    // Get the MaterialX library path within the MaterialX folder.
    _mtlxLibPath = mtlxPath + "/libraries";

    // Create the MaterialX standard library if it doesn't exist.
    if (!s_pStdLib)
    {
        createStdLib();
    }

    // Create a Slang generator and generator context.
    _pGenerator        = make_shared<BSDFShaderGenerator>(_mtlxLibPath);
    _pGeneratorContext = make_unique<MaterialX::GenContext>(_pGenerator);

    // Create unit system.
    _unitSystem   = MaterialX::UnitSystem::create(_pGenerator->getTarget());
    _unitRegistry = MaterialX::UnitConverterRegistry::create();
    MaterialX::UnitTypeDefPtr distanceTypeDef = s_pStdLib->getUnitTypeDef("distance");

    // Add create and register unit converter.
    MaterialX::UnitConverterPtr uconverter =
        MaterialX::LinearUnitConverter::create(distanceTypeDef);
    _unitRegistry->addUnitConverter(distanceTypeDef, uconverter);

    // Setup unit system.
    _unitSystem->loadLibrary(s_pStdLib);
    _unitSystem->setUnitConverterRegistry(_unitRegistry);

    // Get the names of the unit definitions and their indices so client code can access them.
    auto unitDefs = distanceTypeDef->getUnitDefs();
    _units.names.clear();
    _units.indices.clear();
    while (true)
    {
        // Get the name for current index..
        int idx     = (int)_units.names.size();
        string unit = uconverter->getUnitFromInteger(idx);
        if (unit.empty())
            break;

        // Add to array and map.
        _units.indices[unit] = idx;
        _units.names.push_back(unit);
    }

    // Set the unit system in the generator.
    _pGenerator->setUnitSystem(_unitSystem);
    _pGeneratorContext->getOptions().targetDistanceUnit = "centimeter"; // NOTE: this is not used.

    // Setup library search path to find libraries.
    MaterialX::FileSearchPath searchPath;
    searchPath.append(_mtlxLibPath.c_str());
    _pGeneratorContext->registerSourceCodeSearchPath(searchPath);
}

// Convert a path (e.g. foo/bar/value) to a valid C identifier (e.g. foo_bar_value).
string pathToVariableName(const string& propPath)
{
    static constexpr string_view kInvalidChars = " .\\/:~()*+$#@";
    string varName = propPath;
    std::transform(varName.begin(), varName.end(), varName.begin(), [](char c) {
        return kInvalidChars.find(c) != string_view::npos ? '_' : c;
    });
    return varName;
}

// Strip the root document segment from a MaterialX element path.
// MaterialX paths look like "DocumentName/nodegraph/input"; after stripping the
// first segment the result is usable as a short property name or short key.
// If stripLastSegment is true, also removes the last segment (used for texture paths
// where the leaf is the attribute name, not the node name).
string stripRootPathSegment(const string& propPath, bool stripLastSegment = false)
{
    size_t firstSlash = propPath.find('/');
    string res = (firstSlash == string::npos) ? propPath : propPath.substr(firstSlash + 1);
    if (stripLastSegment)
    {
        size_t lastSlash = res.rfind('/');
        if (lastSlash != string::npos)
            res = res.substr(0, lastSlash);
    }
    return res;
}

// Convert property type to Slang/HLSL string type name.
string getShaderStringFromType(PropertyValue::Type type)
{
    switch (type)
    {
    case PropertyValue::Type::Bool:
        return "int";
    case PropertyValue::Type::Int:
        return "int";
    case PropertyValue::Type::Float:
        return "float";
    case PropertyValue::Type::Float2:
        return "float2";
    case PropertyValue::Type::Float3:
        return "float3";
    case PropertyValue::Type::Float4:
        return "float4";
    case PropertyValue::Type::Matrix4:
        return "float4x4";
    default:
        AU_FAIL("Unsupported type for uniform block:%x", type);
        return 0;
    }
}

// Empty dtor in C++ file, to avoid issues with forward declaring MaterialX types.
BSDFCodeGenerator::~BSDFCodeGenerator() {}

void BSDFCodeGenerator::processInput(MaterialX::ShaderInput* input,
    shared_ptr<BSDFCodeGeneratorShader> pBSDFGenShader, const string& bsdfInputVariable,
    string* pSourceOut)
{
    // Do we need local scope to avoid name collisions?
    bool addScope = false;

    // Get the shader stage.
    MaterialX::ShaderStage& ps = pBSDFGenShader->getStage(MaterialX::Stage::PIXEL);

    // Get the connection for the input (warn if null.)
    auto connection = input->getConnection();

    // For adsk compound shader types the flat ShaderGraph exposes the compound node's
    // interface inputs as connections to kShaderGraphName (the top-level
    // graph).  The ACTUAL upstream data source — typically an adsk:bitmap texture node —
    // is also present in the flat graph but is only reachable by searching for a node
    // whose output lists this input as a consumer.  Redirect connection to that node's
    // output so the existing intermediate-node logic (else branch below) samples it
    // correctly instead of falling back to a uniform material-struct read.
    if (connection &&
        connection->getNode()->getName() == kShaderGraphName)
    {
        const MaterialX::ShaderGraph& shaderGraph = pBSDFGenShader->getGraph();

        // Find the non-graph node whose output drives this input via the consumer-list.
        // For adsk compound inputs whose textures are in the application nodegraph (not
        // visible in the flat ShaderGraph after importLibrary), the _adskConnections path
        // below handles them instead.
        auto findExternalOutput = [&]() -> MaterialX::ShaderOutput*
        {
            for (MaterialX::ShaderNode* candidate : shaderGraph.getNodes())
            {
                if (candidate == input->getNode()) continue;
                for (size_t k = 0; k < candidate->numOutputs(); k++)
                {
                    MaterialX::ShaderOutput* out = candidate->getOutput(k);
                    for (MaterialX::ShaderInput* consumer : out->getConnections())
                        if (consumer == input) return out;
                }
            }
            return nullptr;
        };
        MaterialX::ShaderOutput* external = findExternalOutput();

        if (external)
        {
            connection = external;
        }
        else if (!bsdfInputVariable.empty())
        {
            // The external texture nodes are not visible in the flat ShaderGraph for adsk
            // compound inputs that have direct-value connections. For inputs connected
            // externally via nodegraphs, the else-branch handles them correctly already.
            // This block handles direct-value interface inputs using _adskConnections.

            // Use the pre-importLibrary snapshot of connections (_adskConnections),
            // since importLibrary destroys nodegraph connection info in the document.
            auto connIter = _adskConnections.find(input->getName());
            if (connIter != _adskConnections.end())
            {
                const string& srcNodeName = connIter->second.sourceNode;
                if (!srcNodeName.empty())
                {
                    // The texture was registered with path = stripRootPathSegment(ng/srcNode, true) = srcNode.
                    auto texIter = _textureIndexLookup.find(srcNodeName);
                    if (texIter != _textureIndexLookup.end())
                    {
                        const string& samplerName = _textures[texIter->second].name.image;
                        string typeStr =
                            pBSDFGenShader->syntax()->getTypeName(input->getType());
                        string swizzle = (typeStr == "float")  ? ".r"  :
                            (typeStr == "float2") ? ".rg" :
                            (typeStr == "float3" || typeStr == "float4") ? ".rgb" : "";
                        pSourceOut->append(
                            "\t// adsk compound: sample '" + samplerName + "' for '" +
                            input->getName() + "'\n");
                        pSourceOut->append(
                            "\t" + bsdfInputVariable + " = texture(" + samplerName +
                            "_image_parameter, vertexData.texCoord)" + swizzle + ";\n");
                        return;
                    }
                }
            }
        }
        // If no external provider is found the code falls through to the existing
        // top-level handling (material struct or emitVariableDeclaration default).
    }

    // No upstream node connection — use the input's direct value.
    if (!connection)
    {
        // If we're filling a temp variable, check whether this input is a registered
        // material property. If so, read it from the material struct so that values
        // set via setMaterialProperties() are honoured (this is the root cause of the
        // UV-transform regression: rotation_angle/uv_offset/uv_scale were declared but
        // never populated from the struct, so they always stayed at their MTLX defaults).
        if (!bsdfInputVariable.empty())
        {
            auto paramIter = _parameterIndexLookup.find(input->getPath());
            if (paramIter != _parameterIndexLookup.end())
            {
                auto& param = _parameters[paramIter->second];
                if (param.paramType == ParameterType::MaterialProperty)
                {
                    pSourceOut->append(
                        "\t" + bsdfInputVariable + " = material." + param.variableName + ";\n");
                    return;
                }
                if (param.paramType == ParameterType::Texture)
                {
                    pSourceOut->append("\t" + bsdfInputVariable + " = " +
                        param.variableName + "_image_parameter;\n");
                    return;
                }
            }
            // Input has a direct constant value (e.g. transmission=1.0 inside adsk:transparent).
            // Emit it as a literal so it reaches the Aurora Material struct.
            MaterialX::ValuePtr constVal = input->getValue();
            if (constVal)
            {
                pSourceOut->append(
                    "\t" + bsdfInputVariable + " = " + constVal->getValueString() + ";\n");
                return;
            }
        }
        AU_WARN("Input %s has no connection, ignoring.", input->getFullName().c_str());
        return;
    }

    // Get full variable name (with postfix numeral) for connection.
    string variableName = connection->getVariable();
    if (input->getConnection()->getNode()->getName() == kShaderGraphName)
    {
        // If this a connection from the high-level shader graph, its a material input.
        auto inputName = input->getFullName();
        string path    = input->getPath();

        // Special case for inputs that are units, represent as built-in "distance_unit" parameter.
        // TODO: Can we infer this from the mtlx API?  If not we should add this, to avoid
        // hard-coded string searches.
        bool isUnit = false;
        if (inputName.find("unit_unit_to") != string::npos)
        {
            _hasUnits = true;
            isUnit    = true;
            if (_builtInIndexLookup.find("distance_unit") == _builtInIndexLookup.end())
            {
                _builtInIndexLookup["distance_unit"] = (int)_builtIns.size();
                _builtIns                            = { { "int", "distance_unit" } };
            }
        }

        // Process the graph input.
        pSourceOut->append("\t// Graph input " + path + "\n");
        auto paramIter = _parameterIndexLookup.find(path);
        if (!isUnit && paramIter == _parameterIndexLookup.end())
        {
            // MtlX code gen requires a scope, but we comment it out so variable scope not effected.
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                .beginScope(MaterialX::Syntax::CURLY_BRACKETS);

            // If this is not one of the parameters to the setup function write the default value as
            // GLSL.
            _pGenerator->emitVariableDeclaration(input, "", *_pGeneratorContext, ps, true);

            // End the scope for declaration.
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                .endScope(MaterialX::Syntax::CURLY_BRACKETS);

            // Append source for this input.
            pSourceOut->append("\t" + pBSDFGenShader->getNewSource() + ";\n");
        }
        else
        {

            // MtlX code gen requires a scope, but we comment it out so variable scope not effected.
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                .beginScope(MaterialX::Syntax::CURLY_BRACKETS);

            // If this is one of the parameters to the setup function don't write the default value
            // in GLSL.
            _pGenerator->emitVariableDeclaration(input, "", *_pGeneratorContext, ps, false);

            // End the declaration scope.
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                .endScope(MaterialX::Syntax::CURLY_BRACKETS);

            // Append declaration to source.
            pSourceOut->append("\t" + pBSDFGenShader->getNewSource());

            if (isUnit)
            {
                // the unit parameter is always first built-in.
                pSourceOut->append(" = " + _builtIns[0].second + ";\n");
            }
            else
            {
                // Append the parameter name.
                auto& param = _parameters[paramIter->second];
                if (param.paramType == ParameterType::MaterialProperty)
                    pSourceOut->append(" = material." + param.variableName + ";\n");
                else if (param.paramType == ParameterType::Texture)
                    pSourceOut->append(" = " + param.variableName + "_image_parameter;\n");
                param.glslType = pBSDFGenShader->syntax()->getTypeName(input->getType());
            }
        }

        // Set the variable name that will used to generate the output.result.
        variableName = input->getVariable();
    }
    else
    {
        // Get the node this connection is from and its implementation string.
        auto node       = connection->getNode();
        string implName = node->getImplementation().getName();

        // Create a temp variable to store the node output, if this node has already been generated
        // then this will be reused without generating again.
        // TODO: Handle multiple outputs.
        string outputTempVariable =
            "nodeOutTmp_" + connection->getNode()->getName() + "_" + connection->getName();

        // Only process the input if it hasn't already been processed.
        if (_processedNodes.find(node) == _processedNodes.end())
        {
            _processedNodes.insert(node);

            // Generate temp variables for the inputs, to avoid name collisions.
            auto inputs = node->getInputs();
            pSourceOut->append("\t//Temp input variables for " + node->getName() + " \n");

            // Create a temp output variable to store any externally-facing outputs.
            pSourceOut->append("\t" + pBSDFGenShader->syntax()->getTypeName(connection->getType()) +
                " " + outputTempVariable + "; //Temp output variable for " + connection->getName() +
                " \n");

            vector<string> outputVars;
            for (size_t i = 0; i < inputs.size(); i++)
            {
                // Get the input name and connection name it is coming from..
                auto nodeInput = inputs[i];
                string inputTempVariable =
                    "nodeTmp_" + nodeInput->getNode()->getName() + "_" + nodeInput->getName();

                // Create temp variable
                string inputType = pBSDFGenShader->syntax()->getTypeName(nodeInput->getType());
                pSourceOut->append("\t" + inputType + " " + inputTempVariable +
                    "; //Temp input variable for " + nodeInput->getName() + " \n");

                // Add to output variables.(passed to upstream input nodes) and code generator.
                outputVars.push_back(inputTempVariable);
                _pGenerator->addTempInputVariable(nodeInput, inputTempVariable);
            }

            // Recursively process inputs.
            for (size_t i = 0; i < inputs.size(); i++)
            {
                auto nodeInput = inputs[i];
                processInput(nodeInput, pBSDFGenShader, outputVars[i], pSourceOut);
            }

            // Check if we already have a definition for this node's implementation.
            // The definitions are shared between documents, and calls to generate.
            auto defIter           = _definitionMap.find(implName);
            size_t definitionIndex = 0xFFFFFFFF;
            if (defIter != _definitionMap.end())
            {
                definitionIndex = defIter->second;
            }
            else
            {
                // MtlX code gen requires a scope, but we comment it out so variable scope not
                // effected.
                pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
                pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                    .beginScope(MaterialX::Syntax::CURLY_BRACKETS);

                // If not already generated (and not an empty string), store the function
                // definition.
                _pGenerator->emitFunctionDefinition(*node, *_pGeneratorContext, ps);

                // End scope for definition.
                pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
                pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                    .endScope(MaterialX::Syntax::CURLY_BRACKETS);

                string defSource = pBSDFGenShader->getNewSource();
                if (defSource.size())
                {
                    definitionIndex          = _definitions.size();
                    _definitionMap[implName] = definitionIndex;
                    _definitions.push_back(
                        "\n// Definition for implementation " + implName + "\n" + defSource);
                }
            }

            // Begin with comment (referencing definition if there is one)
            pSourceOut->append("\t// Graph input function call " + input->getName());
            if (definitionIndex != 0xFFFFFFFF)
            {
                pSourceOut->append(" (See definition " + implName + ")");
            }
            pSourceOut->append("\n");

            // To avoid name collisions add local scope.
            // TODO: Fix indentation.
            pSourceOut->append("{\n");
            addScope = true;

            // MtlX code gen requires a scope, but we comment it out so variable scope not
            // effected.
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                .beginScope(MaterialX::Syntax::CURLY_BRACKETS);

            // Emit function call for this input.
            _pGenerator->emitFunctionCall(*node, *_pGeneratorContext, ps);

            // End scope for function call.
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL).addValue("//");
            pBSDFGenShader->getStage(MaterialX::Stage::PIXEL)
                .endScope(MaterialX::Syntax::CURLY_BRACKETS);

            pSourceOut->append("\t" + pBSDFGenShader->getNewSource());

            pSourceOut->append("\t" + outputTempVariable);
            pSourceOut->append(" = " + variableName + ";// Output connection\n");
        }
        else
        {
            variableName = outputTempVariable;
        }
    }

    // Copy this output to the provided
    if (bsdfInputVariable.size())
    {
        pSourceOut->append("\t" + bsdfInputVariable);
        pSourceOut->append(" = " + variableName + ";// Output connection\n");
    }

    // End local scope (ensuring output variable setter is enclosed.)
    if (addScope)
    {
        pSourceOut->append("}\n");
    }
}

void BSDFCodeGenerator::clearDefinitions()
{
    // Clear the definitions, which are accumulated after each generate call.
    _definitions.clear();
    _definitionMap.clear();

    // Clear the includes and defs in the shader generator.
    _pGenerator->clearGeneratedDefinitions();
}

int BSDFCodeGenerator::generateDefinitions(string* pResultOut)
{
    // Combine the GLSL code stored in the definitions vector.
    *pResultOut = "";
    for (size_t i = 0; i < _definitions.size(); i++)
    {
        pResultOut->append(_definitions[i]);
    }

    // Return number of definitions.
    return (int)_definitions.size();
}

bool BSDFCodeGenerator::materialXValueToAuroraValue(
    Value* pValueOut, shared_ptr<MaterialX::Value> pMtlXValue)
{
    *pValueOut = Value();

    string glslType = pMtlXValue->getTypeString();
    if (glslType.compare("color3") == 0)
    {
        MaterialX::Color3 valData = pMtlXValue->asA<MaterialX::Color3>();
        *pValueOut                = glm::vec3(valData[0], valData[1], valData[2]);
        return true;
    }
    if (glslType.compare("vector2") == 0)
    {
        MaterialX::Vector2 valData = pMtlXValue->asA<MaterialX::Vector2>();
        *pValueOut                 = glm::vec2(valData[0], valData[1]);
        return true;
    }
    if (glslType.compare("boolean") == 0)
    {
        bool valData = pMtlXValue->asA<bool>();
        *pValueOut   = valData;
        return true;
    }
    if (glslType.compare("integer") == 0)
    {
        int valData = pMtlXValue->asA<int>();
        *pValueOut  = valData;
        return true;
    }
    if (glslType.compare("float") == 0)
    {
        float valData = pMtlXValue->asA<float>();
        *pValueOut    = valData;
        return true;
    }
    if (glslType.compare("string") == 0)
    {
        string valData = pMtlXValue->asA<string>();
        *pValueOut     = valData;
        return true;
    }

    return false;
}

bool BSDFCodeGenerator::materialXValueToAuroraPropertyValue(
    PropertyValue* pValueOut, shared_ptr<MaterialX::Value> pMtlXValue)
{
    *pValueOut = PropertyValue();

    string glslType = pMtlXValue->getTypeString();
    if (glslType.compare("color3") == 0)
    {
        MaterialX::Color3 valData = pMtlXValue->asA<MaterialX::Color3>();
        *pValueOut                = glm::vec3(valData[0], valData[1], valData[2]);
        return true;
    }
    if (glslType.compare("vector2") == 0)
    {
        MaterialX::Vector2 valData = pMtlXValue->asA<MaterialX::Vector2>();
        *pValueOut                 = glm::vec2(valData[0], valData[1]);
        return true;
    }
    if (glslType.compare("vector3") == 0)
    {
        MaterialX::Vector3 valData = pMtlXValue->asA<MaterialX::Vector3>();
        *pValueOut                 = glm::vec3(valData[0], valData[1], valData[2]);
        return true;
    }
    if (glslType.compare("vector4") == 0)
    {
        MaterialX::Vector4 valData = pMtlXValue->asA<MaterialX::Vector4>();
        *pValueOut                 = glm::vec4(valData[0], valData[1], valData[2], valData[3]);
        return true;
    }
    if (glslType.compare("boolean") == 0)
    {
        bool valData = pMtlXValue->asA<bool>();
        *pValueOut   = valData;
        return true;
    }
    if (glslType.compare("integer") == 0)
    {
        int valData = pMtlXValue->asA<int>();
        *pValueOut  = valData;
        return true;
    }
    if (glslType.compare("float") == 0)
    {
        float valData = pMtlXValue->asA<float>();
        *pValueOut    = valData;
        return true;
    }
    if (glslType.compare("string") == 0)
    {
        string valData = pMtlXValue->asA<string>();
        *pValueOut     = valData;
        return true;
    }
    AU_WARN("Unrecognized MaterialX value type:%s", glslType.c_str());
    return false;
}

PropertyValue::Type BSDFCodeGenerator::glslTypeToAuroraType(const string glslType)
{
    // Map Slang/HLSL type names to Aurora property types.
    if (glslType.compare("float3") == 0)
        return PropertyValue::Type::Float3;
    if (glslType.compare("float2") == 0)
        return PropertyValue::Type::Float2;
    if (glslType.compare("float") == 0)
        return PropertyValue::Type::Float;
    if (glslType.compare("int") == 0)
        return PropertyValue::Type::Int;
    if (glslType.compare("bool") == 0)
        return PropertyValue::Type::Bool;

    // Fail if no valid mapping found.
    AU_FAIL("Unsupported shader type %s", glslType.c_str());
    return PropertyValue::Type::Undefined;
}

namespace
{

// Resolves a MaterialX filename against its document's folder, returning an absolute path if found
// or the value unchanged if not. Unresolved references reach the asset manager as-authored, enabling
// host callbacks and preserving error messages for missing textures.
// NOTE: mx::flattenFilenames() cannot be used; it rewrites unresolved paths and skips legacy <parameter> forms.
string resolveTextureFilename(const MaterialX::ElementPtr& elem, const string& value,
    const MaterialX::FileSearchPath& searchPath)
{
    // Empty or no search path, return unchanged.
    if (value.empty() || searchPath.isEmpty())
        return value;

    // Absolute paths and URIs are already resolved, so leave it unchanged.
    MaterialX::FilePath filePath(value);
    if (filePath.isAbsolute() || value.find("://") != string::npos)
        return value;

    // Normalize paths to collapsed form for consistent cache keys.
    auto normalized = [](const MaterialX::FilePath& path) {
        return path.getNormalized().asString(MaterialX::FilePath::FormatPosix);
    };

    // Try document's "fileprefix" first, then fallback to plain relative path.
    string prefixed = elem->createStringResolver()->resolve(value, MaterialX::FILENAME_TYPE_STRING);
    MaterialX::FilePath resolved = searchPath.find(MaterialX::FilePath(prefixed));
    if (resolved.exists())
        return normalized(resolved);

    resolved = searchPath.find(filePath);
    if (resolved.exists())
        return normalized(resolved);

    return value;
}

} // namespace

bool BSDFCodeGenerator::generate(const string& document, BSDFCodeGenerator::Result* pResultOut,
    const set<string> supportedBSDFInputs, const string& overrideDocumentName,
    const string& materialName, const string& baseDirectory)
{
    // Processed MaterialX document string.
    string processedMtlXDocument;

    // Process the document string to replace document name if override name provided.
    if (!overrideDocumentName.empty())
    {
        // Regular expression to find strings in the form:
        //     <materialx version="1.38" colorspace="lin_rec709">  <standard_surface name =
        //     "XID_PlasticBlack"
        // and then retrieve document name: XID_PlasticBlack
        std::regex rgx("<\\s*materialx[^>]+>\\s*<\\s*\\S+\\s+name=\"([^\"]+)\"");
        std::smatch match;

        // Create a copy of document string.
        processedMtlXDocument = document;

        // Search for matches to the document name reg exp.
        if (std::regex_search(processedMtlXDocument, match, rgx))
        {
            // Retrieve the sub-expression with the document name.
            string documentName = match[1];

            // Replace all occurrences of document name with the override value.
            processedMtlXDocument =
                Foundation::replace(processedMtlXDocument, documentName, overrideDocumentName);
        }
        else
        {
            // Warn if the regular expression fails.
            AU_WARN("Failed to find document name in MaterialX XML");
        }
    }

    // Get reference to original or processed materialX document string.
    const string& mtlXDocument = processedMtlXDocument.empty() ? document : processedMtlXDocument;

    // Clear any previous data.
    _pGenerator->clearTempVariables();
    _processedNodes.clear();
    _parameters.clear();
    _parameterIndexLookup.clear();
    _builtInIndexLookup.clear();
    _materialProperties.clear();
    _materialPropertyDefaults.clear();
    _textures.clear();
    _builtIns.clear();
    _hasUnits = false;

    // Clear the setup code string.
    pResultOut->materialSetupCode = "";

    // Search path for texture references. Empty for string documents.
    MaterialX::FileSearchPath textureSearchPath;
    if (!baseDirectory.empty())
        textureSearchPath.append(MaterialX::FilePath(baseDirectory));

    // XIncludes additionally resolve against the MaterialX library folder.
    MaterialX::FileSearchPath readSearchPath = textureSearchPath;
    readSearchPath.append(MaterialX::FilePath(_mtlxLibPath));

    // Create new document object.
    MaterialX::DocumentPtr mtlxDocument = MaterialX::createDocument();

    // Read the XML into a document.
    try
    {
        // Resolve XIncludes relative to the document rather than the process working directory.
        MaterialX::XmlReadOptions readOptions;
        readOptions.readXIncludeFunction = [](MaterialX::DocumentPtr pDoc,
                                               const MaterialX::FilePath& filename,
                                               const MaterialX::FileSearchPath& searchPath,
                                               const MaterialX::XmlReadOptions* pOptions) {
            MaterialX::FilePath resolvedFilename = searchPath.find(filename);
            if (resolvedFilename.exists())
                readFromXmlFile(pDoc, resolvedFilename, searchPath, pOptions);
            else
                AU_ERROR("Include file not found: %s", filename.asString().c_str());
        };

        MaterialX::readFromXmlString(mtlxDocument, mtlXDocument, readSearchPath, &readOptions);
    }
    catch (const MaterialX::Exception& exception)
    {
        AU_ERROR("Failed to read MaterialX from document:\n%s\n", exception.what());
        return false;
    }
    // Write unit registry.
    _unitRegistry->write(mtlxDocument);

    // Return false and print error message, if any.
    string errorMessage;
    if (!mtlxDocument->validate(&errorMessage))
    {
        AU_ERROR("Invalid MaterialX document:\n%s", errorMessage.c_str());
        return false;
    }

    // Capture nodegraph connections from the top-level compound node NOW — before
    // importLibrary() destroys them by resolving/overwriting connected inputs.
    _adskConnections.clear();
    for (auto topNode : mtlxDocument->getNodes())
    {
        for (auto inp : topNode->getInputs())
        {
            if (!inp->getNodeGraphString().empty())
            {
                string ngName  = inp->getNodeGraphString();
                string outName = inp->getOutputString();
                // Follow the output to its source node name.
                string srcName;
                auto ng = mtlxDocument->getNodeGraph(ngName);
                if (ng)
                {
                    auto ngOut = ng->getOutput(outName);
                    if (ngOut) srcName = ngOut->getNodeName();
                }
                _adskConnections[inp->getName()] = { ngName, outName, srcName };
            }
        }
    }
    // Find all the terminal input values that will become the setup function parameters.
    vector<MaterialX::ElementPtr> stringValues;
    _textureIndexLookup.clear();
    // Deduplicate properties by short name: the traversal visits both application
    // elements (e.g. MaterialXDocument/opaque_mfp_modifier) and imported nodedef
    // elements (e.g. ND_adsk_opaque/opaque_mfp_modifier).  Both reduce to the same
    // short name after stripRootPathSegment.  Without deduplication PTScene sets the
    // property twice — the nodedef default (typically white/zero) overwrites the
    // instance value.  Keep only the FIRST occurrence so application values always win.
    map<string, bool> seenPropertyShortNames;
    for (MaterialX::ElementPtr elem : mtlxDocument->traverseTree())
    {
        // Get full path to node.
        string path = elem->getNamePath();

        // Initialize parameter struct to be filled in if parameter is found.
        Parameter param;
        param.parameterIndex = (int)_parameters.size();

        // Have we found a parameter?
        bool foundParam = false;

        MaterialX::ValueElementPtr valueElem = elem->asA<MaterialX::ValueElement>();
        if (valueElem && valueElem->isA<MaterialX::Input>() && valueElem->hasValue())
        {
            // All ValueElement's are parameters.
            foundParam = true;

            // Create a parameter object from the ValueElement's input value (adsk texture node
            // values will be represented this way).
            auto type = valueElem->getType();

            // Fill in parameter based on type.
            if (type.compare("filename") == 0)
            {
                // Create texture parameter from the file ValueElement.
                // Use the short processed path as the texture identifier, but fall back to the
                // full path if the short path collides (e.g. two top-level tiledimage nodes both
                // have a "file" parameter that reduces to the same short path).
                string shortPath = stripRootPathSegment(path, true);
                param.path = _textureIndexLookup.count(shortPath) ? pathToVariableName(path) : shortPath;
                param.variableName = pathToVariableName(param.path);
                param.index        = (int)_textures.size();
                param.paramType    = ParameterType::Texture;
                param.type         = "sampler2D";

                // Create the texture definition for this parameter.
                TextureDefinition tex;
                tex.name            = TextureIdentifier(param.path, param.path + "_sampler");
                tex.defaultFilename = resolveTextureFilename(
                    elem, valueElem->getValue()->asA<string>(), textureSearchPath);

                // Set linearize to if no color space or srgb_texture color space.
                string colorSpace = valueElem->getColorSpace();
                tex.linearize     = colorSpace.empty() || colorSpace.compare("srgb_texture") == 0;

                _textures.push_back(tex);
                _textureIndexLookup[param.path] = param.index;
            }
            else if (type.compare("string") == 0)
            {
                // String parameters are hardcoded texture properties (e.g. wrap mode), must be
                // post-processed.
                stringValues.push_back(elem);
            }
            else
            {
                // All other ValueElement types become material properties.
                param.path         = stripRootPathSegment(path, false); // short name for external lookup
                param.variableName = pathToVariableName(path); // full path for unique struct field
                param.index        = (int)_materialProperties.size();
                param.paramType    = ParameterType::MaterialProperty;
                param.type         = valueElem->getType();

                // Create uniform block property definition for parameter.
                PropertyValue propVal;
                if (!materialXValueToAuroraPropertyValue(&propVal, valueElem->getValue()))
                    continue;
                // String values (e.g. displacementshader with empty value) don't map to
                // uniform block members — skip them.
                if (propVal.type == PropertyValue::Type::String ||
                    propVal.type == PropertyValue::Type::Strings ||
                    propVal.type == PropertyValue::Type::Undefined)
                    continue;
                // Skip if another element with this short name was already registered.
                if (seenPropertyShortNames.count(param.path))
                    continue;
                seenPropertyShortNames[param.path] = true;
                UniformBufferPropertyDefinition propDef(
                    param.path, param.variableName, propVal.type);
                _materialProperties.push_back(propDef);
                _materialPropertyDefaults.push_back(propVal);
            }
        }
        else
        {

            // image nodes and their children are not represented by ValueElement for some reason,
            // so get the type as attribute.
            string type = elem->getAttribute("type");
            if (!type.empty())
            {
                // Process string and filename nodes.
                if (type.compare("filename") == 0)
                {
                    // Found a filename parameter.
                    foundParam = true;

                    // Create texture parameter (same collision guard as the ValueElement path).
                    string shortPath = stripRootPathSegment(path, true);
                    param.path = _textureIndexLookup.count(shortPath) ? pathToVariableName(path) : shortPath;
                    param.variableName = pathToVariableName(param.path);
                    param.index        = (int)_textures.size();
                    param.paramType    = ParameterType::Texture;
                    param.type         = "sampler2D";

                    // Create the texture definition for this parameter.
                    TextureDefinition tex;
                    tex.name            = TextureIdentifier(param.path, param.path + "_sampler");
                    tex.defaultFilename = resolveTextureFilename(
                        elem, elem->getAttribute("value"), textureSearchPath);

                    // Set linearize to if no color space or srgb_texture color space.
                    string colorSpace = elem->getAttribute("colorspace");
                    tex.linearize = colorSpace.empty() || colorSpace.compare("srgb_texture") == 0;

                    _textures.push_back(tex);
                    _textureIndexLookup[param.path] = param.index;
                }
                else if (type.compare("string") == 0)
                {
                    // Found a string parameter.
                    foundParam = true;

                    // String parameters are hardcoded texture properties (e.g. wrap mode), must be
                    // post-processed.
                    stringValues.push_back(elem);
                }
            }
        }

        // Add to setup function parameters.
        if (foundParam && !param.variableName.empty())
        {
            _parameterIndexLookup[path] = (int)_parameters.size();
            _parameters.push_back(param);
        }
    }

    // Process the hardcoded texture properties that will become sampler settings.
    // TODO: Fix this in MaterialX, so we have actual sampler objects, not error prone hard coded
    // magic property names.
    for (MaterialX::ElementPtr elem : stringValues)
    {
        string path    = elem->getNamePath();
        string txtPath = stripRootPathSegment(path, true);
        string valData = elem->getAttribute("value");
        auto iter      = _textureIndexLookup.find(txtPath);
        if (iter != _textureIndexLookup.end())
        {
            auto& texture = _textures[iter->second];
            if (elem->getName().compare("uaddressmode") == 0)
            {
                texture.addressModeU = valData;
            }
            else if (elem->getName().compare("vaddressmode") == 0)
            {
                texture.addressModeV = valData;
            }
        }
    }

    // Import the standard library.
    mtlxDocument->importLibrary(s_pStdLib);

    // Setup include paths.
    // TODO: This is just a guess.  How do we ensure all required includes are provided?
    MaterialX::StringMap& tokenSub =
        const_cast<MaterialX::StringMap&>(_pGenerator->getTokenSubstitutions());
    tokenSub["$fileTransformUv"] = "stdlib/genglsl/lib/mx_transform_uv.glsl";

    // Find renderable nodes.
    vector<MaterialX::TypedElementPtr> elements =
        MaterialX::findRenderableMaterialNodes(mtlxDocument);

    // Return false if no renderable nodes.
    // TODO: Better error handling.
    if (elements.size() == 0)
    {
        AU_ERROR("No renderable nodes in MaterialX document");
        return false;
    }

    // Use the named material if specified and found; otherwise fall back to the first.
    string materialNodeName = elements[0]->getName();
    if (!materialName.empty())
    {
        for (const auto& elem : elements)
        {
            if (elem->getName() == materialName)
            {
                materialNodeName = materialName;
                break;
            }
        }
    }

    // Get the material nodes, return false if empty.
    // TODO: Better error handling.
    auto materialNodes = mtlxDocument->getMaterialNodes();
    if (elements.size() == 0)
    {
        AU_ERROR("Empty material in MaterialX document");
        return false;
    }

    // Find the material node using name from element.
    MaterialX::NodePtr materialNode = nullptr;
    for (size_t i = 0; i < materialNodes.size(); i++)
    {
        if (materialNodes[i]->getName() == materialNodeName)
        {
            materialNode = materialNodes[i];
            break;
        }
    }

    // Return false if find failed.
    // TODO: Better error handling.
    if (materialNode == nullptr)
    {
        AU_ERROR("Failed to find material node");
        return false;
    }

    // Get the shader nodes.
    vector<MaterialX::NodePtr> shaderNodes = MaterialX::getShaderNodes(materialNode);
    if (shaderNodes.empty())
    {
        AU_ERROR("No shader nodes in MaterialX document");
        return false;
    }

    // Find the surface node for shader. Prefer the configured category (standard_surface by
    // default), but fall back to any surface-shader-typed node so that materials using
    // alternative surface shaders (e.g. adsk:layered for Prism materials) are not silently
    // rejected as a solid-grey default material.
    MaterialX::TypedElementPtr shaderNodeElement = nullptr;
    MaterialX::TypedElementPtr fallbackShaderNode = nullptr;
    for (MaterialX::NodePtr shaderNode : shaderNodes)
    {
        if (shaderNode->getType() == MaterialX::SURFACE_SHADER_TYPE_STRING)
        {
            if (shaderNode->getCategory() == _surfaceShaderNodeCategory)
            {
                shaderNodeElement = shaderNode;
                break; // exact match — stop searching
            }
            if (!fallbackShaderNode)
                fallbackShaderNode = shaderNode; // any other surfaceshader
        }
    }
    if (!shaderNodeElement)
        shaderNodeElement = fallbackShaderNode;
    if (!shaderNodeElement)
    {
        AU_ERROR("Failed to find surface shader in material");
        return false;
    }

    // Get the node for MaterialX shader.
    MaterialX::NodePtr shaderNode = shaderNodeElement->asA<MaterialX::Node>();

    // Build a set of the BSDF inputs used by the shader nodes.  These will be the outputs to the
    // setup function.
    auto graphInputs = shaderNode->getInputs();
    set<string> bsdfInputSet;
    for (auto gi : graphInputs)
    {
        string bsdfInputName = gi->getName();
        if (supportedBSDFInputs.empty() ||
            supportedBSDFInputs.find(bsdfInputName) != supportedBSDFInputs.end())
            bsdfInputSet.insert(bsdfInputName);
    }

    // Get the implementation for the node.
    MaterialX::InterfaceElementPtr shaderNodeDefImpl = shaderNode->getImplementation();
    if (!shaderNodeDefImpl)
    {
        AU_ERROR("Failed to find nodegraph implementation for the surface shader");
        return false;
    }
    string surfaceShaderNodeType = shaderNodeDefImpl->getName();

    // Create a shader graph from the surface node.
    // Using shaderNodeElement (not materialNode) is important for adsk compound types: it keeps
    // external texture nodes (adsk:bitmap etc.) visible in the flat graph as siblings of the
    // compound, connected to its interface sockets.  materialNode would hide them inside the
    // unexpanded compound and make them unreachable.
    MaterialX::ShaderGraphPtr graph;
    try
    {
        graph = MaterialX::ShaderGraph::create(
            nullptr, kShaderGraphName, shaderNodeElement, *_pGeneratorContext);
    }
    catch (MaterialX::ExceptionShaderGenError& ex)
    {
        AU_ERROR("Exception in MaterialX code:%s", ex.what());
        return false;
    }
    shared_ptr<BSDFCodeGeneratorShader> pBSDFGenShader =
        make_shared<BSDFCodeGeneratorShader>("BSDFCodeGeneratorShader", graph);
    MaterialX::ShaderPtr shader = dynamic_pointer_cast<MaterialX::Shader>(pBSDFGenShader);

    // Find the surface shader node.
    //
    // Since MaterialX 1.39 the implementation name of a nodegraph-implemented node no longer
    // matches that element name, so the name comparison fails and the material silently falls back
    // to the default. Identify the surface node by SURFACE classification instead, while the
    // implementation-name match is retained only as a fallback.
    MaterialX::ShaderNode* surfaceShaderNode = nullptr;
    for (MaterialX::ShaderNode* node : graph->getNodes())
    {
        if (node->getImplementation().getName() == surfaceShaderNodeType)
        {
            surfaceShaderNode = node;
            break;
        }
        if (!surfaceShaderNode &&
            node->hasClassification(MaterialX::ShaderNode::Classification::SURFACE))
        {
            for (auto* inp : node->getInputs())
            {
                if (bsdfInputSet.find(inp->getName()) != bsdfInputSet.end())
                {
                    surfaceShaderNode = node;
                    break;
                }
            }
        }
    }
    // Find the inner standard_surface node (if the surface shader is an adsk compound).
    // The flat shader graph for adsk compounds does NOT expose inner implementation nodes
    // (e.g. standard_surface0 inside NG_adsk_transparent) as separate ShaderNodes.
    // Instead, search the MaterialX document's nodegraph implementation directly.
    // This gives access to constant inputs (e.g. transmission=1, thin_walled=true) that
    // are fixed by the compound but not exposed as compound interface inputs.
    MaterialX::NodePtr innerStandardSurfaceMtlx = nullptr;
    {
        const string& foundImplName = surfaceShaderNode
            ? surfaceShaderNode->getImplementation().getName() : "";
        const bool foundIsCompound = surfaceShaderNode &&
            foundImplName.find(_surfaceShaderNodeCategory) == string::npos;
        if (foundIsCompound && shaderNodeElement)
        {
            // Get the compound's nodegraph implementation from the document.
            auto nodeDefImpl = shaderNodeElement->asA<MaterialX::Node>()->getImplementation();
            if (nodeDefImpl)
            {
                auto nodegraph = nodeDefImpl->asA<MaterialX::NodeGraph>();
                if (!nodegraph)
                {
                    // Might be an InterfaceElement pointing to a nodegraph by name.
                    nodegraph = mtlxDocument->getNodeGraph(nodeDefImpl->getName());
                }
                if (nodegraph)
                {
                    for (auto node : nodegraph->getNodes())
                    {
                        if (node->getCategory() == _surfaceShaderNodeCategory)
                        {
                            innerStandardSurfaceMtlx = node;
                            break;
                        }
                    }
                }
            }
        }
    }

    // Third fallback: if still not found, accept any SURFACE-classified node.
    if (!surfaceShaderNode)
    {
        for (MaterialX::ShaderNode* node : graph->getNodes())
        {
            if (node->hasClassification(MaterialX::ShaderNode::Classification::SURFACE))
            {
                surfaceShaderNode = node;
                break;
            }
        }
        if (surfaceShaderNode)
        {
            bsdfInputSet.clear();
            for (MaterialX::ShaderInput* inp : surfaceShaderNode->getInputs())
            {
                const string& nm = inp->getName();
                if (supportedBSDFInputs.empty() || supportedBSDFInputs.count(nm))
                    bsdfInputSet.insert(nm);
            }
        }
    }

    if (!surfaceShaderNode)
    {
        AU_ERROR("No surface shader node of type %s found", surfaceShaderNodeType.c_str());
        return false;
    }

    // Create the active inputs and outputs.
    _activeBSDFInputs.clear();
    _activeBSDFInputNames.clear();

    // Build the body of the setup function from the surface shader node inputs.
    string functionBody      = "";
    auto surfaceShaderInputs = surfaceShaderNode->getInputs();
    for (size_t ssi = 0; ssi < surfaceShaderInputs.size(); ssi++)
    {
        // Is this shader input one of the outputs we are interested in ?
        auto surfaceShaderInput = surfaceShaderInputs[ssi];
        string inputName        = surfaceShaderInput->getName();

        // Process inputs that are in the set of BSDF inputs for this material.
        string bsdfInputVariable;
        if (bsdfInputSet.find(inputName) != bsdfInputSet.end())
            bsdfInputVariable = inputName;
        if (!bsdfInputVariable.empty())
        {
            // Process the shader input.
            processInput(surfaceShaderInput, pBSDFGenShader, bsdfInputVariable, &functionBody);

            // Add to list of active BSDF inputs.
            _activeBSDFInputNames.push_back(bsdfInputVariable);
            _activeBSDFInputs[bsdfInputVariable] =
                pBSDFGenShader->syntax()->getTypeName(surfaceShaderInput->getType());
        };
    }

    // Emit constant inputs from the inner standard_surface node that are NOT connected to
    // any compound interface input (e.g. metalness=1 in adsk:metal, thin_walled=true in
    // adsk:glazing).  Treat them as additional OUT params of the setup function so that
    // MaterialGenerator can write them to the Material struct through the normal BSDF
    // output path, without a separate side-channel.
    // The flat ShaderGraph doesn't expose inner implementation nodes, so we use the
    // document-level nodegraph to find the standard_surface node directly.
    if (innerStandardSurfaceMtlx)
    {
        for (auto inp : innerStandardSurfaceMtlx->getInputs())
        {
            const string& nm = inp->getName();
            if (bsdfInputSet.count(nm))
                continue; // already handled as a variable BSDF output via interface
            if (!inp->getNodeName().empty() || !inp->getInterfaceName().empty())
                continue; // computed or interface-connected — not a plain constant
            MaterialX::ValuePtr val = inp->getValue();
            if (!val)
                continue;
            // Emit the constant inline in the function body and register as an OUT param
            // so the wrapper writes it to material.<field> via _bsdfInputParamMapping.
            const string& type = inp->getType();
            if (type == "float" || type == "boolean")
            {
                string slangType = (type == "boolean") ? "bool" : "float";
                functionBody += "\t" + nm + " = " + val->getValueString() + ";\n";
                _activeBSDFInputNames.push_back(nm);
                _activeBSDFInputs[nm] = slangType;
            }
        }
    }

    // Set the material properties and textures in result.
    pResultOut->materialProperties       = _materialProperties;
    pResultOut->materialPropertyDefaults = _materialPropertyDefaults;
    pResultOut->textureDefaults          = _textures;
    pResultOut->hasUnits                 = _hasUnits;

    // Set the texture names in the result.
    pResultOut->textures.clear();
    for (size_t i = 0; i < pResultOut->textureDefaults.size(); i++)
    {
        pResultOut->textures.push_back(pResultOut->textureDefaults[i].name);
    }

    // Create the contents of the material struct.
    string structProperties;
    for (size_t i = 0; i < pResultOut->materialProperties.size(); i++)
    {
        string glslType = getShaderStringFromType(pResultOut->materialProperties[i].type);

        structProperties.append(
            "\t" + glslType + " " + pResultOut->materialProperties[i].variableName + ";\n");
    }

    // Create a hash from the contents of the setup function and the material struct. This is used
    // to uniquely identify the shader code generated for this material.  It is possible to have
    // identical functions with different material structs (as struct properties can be unused.)
    // TODO: Strip out unused material parameters.
    size_t structHash        = hash<string> {}(structProperties);
    pResultOut->functionHash = hash<string> {}(functionBody);
    Foundation::hashCombine(pResultOut->functionHash, structHash);

    // Create setup function name from hash.
    stringstream sstream;
    sstream << "setupMaterial_" << Foundation::sHash(pResultOut->functionHash);
    pResultOut->setupFunctionName = sstream.str();

    // Create material struct type name from hash.
    sstream = stringstream();
    sstream << "Material_" << Foundation::sHash(pResultOut->functionHash);
    pResultOut->materialStructName = sstream.str();

    // Create the GLSL code for the material struct (containing all material properties).
    pResultOut->materialStructCode = "struct " + pResultOut->materialStructName + " {\n";
    pResultOut->materialStructCode.append(structProperties);
    pResultOut->materialStructCode.append("};\n");

    // Create the function prototype from the function name, active inputs and outputs.
    pResultOut->materialSetupCode = "void " + pResultOut->setupFunctionName + "(\n";

    // Keep track of total input and output parameter count.
    [[maybe_unused]] int numParams = 0;

    // The first argument is always the material struct.
    pResultOut->materialSetupCode.append("\t" + pResultOut->materialStructName + " material");

    // Add the texture inputs to the function prototype.
    for (size_t i = 0; i < _textures.size(); i++)
    {
        pResultOut->materialSetupCode.append(",\n");

        // Add the code for this input to the prototype.
        pResultOut->materialSetupCode.append(
            "\tsampler2D " + _textures[i].name.image + "_image_parameter");

        numParams++;
    }

    // The distance unit (if used) is last input parameter in setup function prototype.
    if (_hasUnits)
    {
        pResultOut->materialSetupCode.append(",\n");

        // Add the code for the distance unit.
        pResultOut->materialSetupCode.append("\tint " + _builtIns[0].second);

        numParams++;
    }

    // The active BSDF inputs become output parameters to the function prototype.
    pResultOut->bsdfInputs.clear();
    for (auto bsdfInputName : _activeBSDFInputNames)
    {
        auto activeTypeIter = _activeBSDFInputs.find(bsdfInputName);
        if (activeTypeIter != _activeBSDFInputs.end())
        {
            // Create variable name using output name and suffix.
            string outputVarName = bsdfInputName;

            // Append comma to previous line, if any.
            pResultOut->materialSetupCode.append(",\n");

            // Convert GLSL type to Aurora type enum.
            PropertyValue::Type auroraType = glslTypeToAuroraType(activeTypeIter->second);

            // Add this output to the results.
            pResultOut->bsdfInputs.push_back({ bsdfInputName, auroraType });

            // Add the code for this output to the prototype.
            pResultOut->materialSetupCode.append(
                "\tout " + activeTypeIter->second + " " + outputVarName);

            // Increment parameter count.
            numParams++;
        }
    }

    // Add body wrapped in braces.
    pResultOut->materialSetupCode.append(")\n{\n");
    pResultOut->materialSetupCode.append(functionBody);
    pResultOut->materialSetupCode.append("}\n");

    return true;
};

} // namespace MaterialXCodeGen
} // namespace Aurora
