// Copyright 2026 Autodesk, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#pragma once

#include "UniformBuffer.h"
#include <MaterialXCore/Generated.h>

// Forward declare MaterialX types.
MATERIALX_NAMESPACE_BEGIN
class Document;
class FileSearchPath;
class ShaderGenerator;
class GenContext;
class ShaderStage;
class ShaderInput;
class Value;
class UnitConverterRegistry;
class UnitSystem;
class ShaderNode;
class TypeDesc;
MATERIALX_NAMESPACE_END

#include "Properties.h"

BEGIN_AURORA

namespace MaterialXCodeGen
{

// Forward declare shader class (used internally for codegen)
class BSDFCodeGeneratorShader;
class BSDFShaderGenerator;

/// MaterialX code generator for BSDF and material setup. Generates Slang code for pathtracing.
/// TODO: Currently only generates the material setup function and associated metadata, not the
/// BSDF.
class BSDFCodeGenerator
{
public:
    // The MaterialX units.
    struct Units
    {
        // Unit names.
        std::vector<string> names;
        // Indices for units used in shaders.
        std::map<string, int> indices;
    };

    // The BSDF inputs that are produced by the setup function.
    struct BSDFInput
    {
        /// Input name
        string name;
        /// Input type as PropertyValue type enum
        PropertyValue::Type type = PropertyValue::Type::Undefined;
    };

    /// Code generation result.
    struct Result
    {
        /// Unique hash for the generated code.
        size_t functionHash = 0;
        /// The generated Slang code for the material setup function.
        string materialSetupCode;
        /// The Slang struct type definition for the material constant buffer.
        string materialStructCode;
        /// Name of the generated setup function.
        string setupFunctionName;
        /// Name of the generated material struct type.
        string materialStructName;
        /// Material properties in the material uniform struct.
        vector<UniformBufferPropertyDefinition> materialProperties;
        /// Texture identifiers used by the setup function.
        vector<TextureIdentifier> textures;
        /// BSDF inputs output by the setup function.
        vector<BSDFInput> bsdfInputs;
        /// True if the setup function takes a distance-unit integer parameter.
        bool hasUnits = false;
        /// Default values for material properties.
        vector<PropertyValue> materialPropertyDefaults;
        /// Default values for textures.
        vector<TextureDefinition> textureDefaults;
    };

    /// \param surfaceShaderNodeCategory The surface shader category to code generate material
    /// inputs for. \param mtlxPath The search path for the materialX assets, including the library
    /// assets in the 'libraries' folder.
    BSDFCodeGenerator(const string& mtlxPath = "./MaterialX", const string& = "standard_surface");

    ~BSDFCodeGenerator();

    /// \desc Run the code generator on a MaterialX document.
    /// \param.document MaterialX XML document string.
    /// \param inputParameterMapper Function used to map a parameter in the MaterialX network an
    /// input parameter in the setup function.
    /// \param outputParameterMapper Function used to map a parameter in the MaterialX network an
    /// output parameter in the setup function.
    /// \param pResultOut Code generation result output. If materialName is non-empty, the material
    /// with that name in the document is used; otherwise the first renderable material is used.
    /// \param baseDirectory Source folder for resolving relative textures and XIncludes. If empty,
    /// filenames are passed through unchanged, as for an in-memory document.
    bool generate(const string& document, Result* pResultOut,
        const set<string> supportedBSDFInputs = {}, const string& overrideDocumentName = "",
        const string& materialName = "", const string& baseDirectory = "");

    /// \desc Generate the shared Slang definitions for all the documents generated by this
    /// generator. Will clear the shared definitions.
    /// \param pDefinitionCodeOut Slang definition string.
    int generateDefinitions(string* pDefinitionCodeOut);

    /// Clear the definition shader code, which is accumulated after each generateDefinitions call.
    void clearDefinitions();

    // Get the units used by materialX.
    const Units& units() { return _units; }

protected:
    enum ParameterType
    {
        MaterialProperty,
        Texture,
        BuiltIn
    };

    struct Parameter
    {
        string variableName;
        string path;
        string type;
        string glslType;
        int index               = 0;
        int parameterIndex      = 0;
        ParameterType paramType = MaterialProperty;
    };

    // Convert GLSL type string to Aurora type (asserts if conversion fails.)
    PropertyValue::Type glslTypeToAuroraType(const string glslType);

    // Convert MaterialX value to Aurora value (asserts if conversion fails.)
    bool materialXValueToAuroraValue(Value* pValueOut, shared_ptr<MaterialX::Value> pMtlXValue);

    bool materialXValueToAuroraPropertyValue(
        PropertyValue* pValueOut, shared_ptr<MaterialX::Value> pMtlXValue);

    // Process a MaterialX shader input.
    void processInput(MaterialX::ShaderInput* input,
        shared_ptr<BSDFCodeGeneratorShader> pBSDFGenShader, const string& outputVariable,
        string* pSourceOut);

    // Create the static MaterialX standard library.
    void createStdLib();

    // Static MaterialX standard library shared across all instances.
    static shared_ptr<MaterialX::Document> s_pStdLib;

    // The Slang shader generator used internally.
    shared_ptr<BSDFShaderGenerator> _pGenerator;

    // The shader context used internally.
    unique_ptr<MaterialX::GenContext> _pGeneratorContext;

    // Current active material inputs and outputs.
    map<string, string> _activeBSDFInputs;
    map<string, int> _parameterIndexLookup;
    map<string, int> _builtInIndexLookup;
    vector<Parameter> _parameters;
    vector<UniformBufferPropertyDefinition> _materialProperties;
    vector<PropertyValue> _materialPropertyDefaults;
    vector<TextureDefinition> _textures;
    vector<pair<string, string>> _builtIns;
    vector<string> _activeBSDFInputNames;

    // Definition look-up.
    map<string, size_t> _definitionMap;
    vector<string> _definitions;

    // The surface shader category to code generate inputs for.
    string _surfaceShaderNodeCategory;

    // The units for MaterialX;
    Units _units;

    shared_ptr<MaterialX::UnitSystem> _unitSystem;
    shared_ptr<MaterialX::UnitConverterRegistry> _unitRegistry;
    set<MaterialX::ShaderNode*> _processedNodes;
    string _mtlxLibPath;
    bool _hasUnits = false;


    // Map from texture path (param.path) to texture index (into _textures).
    map<string, int> _textureIndexLookup;

    // Nodegraph connections captured BEFORE importLibrary destroys them.
    // Maps compound-node input name → (nodegraph_name, output_name, source_node_name).
    struct AdskConnection { string nodegraph, output, sourceNode; };
    map<string, AdskConnection> _adskConnections;
};

} // namespace MaterialXCodeGen

END_AURORA
